# -*- coding: utf-8 -*-
"""pythonlearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1685wDuKajFM4_IeTtEESHTaOWmh75Nnv
"""

name = input("What is your name? ")
age = int(input("How old are you? "))
print(f"Hello {name}, you are {age} years old!")

number = int(input("Enter a number: "))
if number == 0 :
 print("Zero")
elif number > 0:
  print("Positive")
else:
  print("Negative")

number = int(input("Enter a number: "))
for i in range (number):
  print(i)

print("Blast off")

number = int(input("Enter a number: "))

for i in range(number, 0, -1):
    print(i)

print("Blast off! 🚀") #Claude fixed version

def calculator (a, b):
  return a * b

result = 4 * 6
print(result)

def add(a, b):
  return  a + b

result = 6 + 5
print(result)

def calculator (a, b):
  return a - b

result = 4 - 6
print(result)

def calculater (a, b):
  return a / b

result = 4 / 6
print(result)

def calculator(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        return a / b
    else:
        return "Invalid operation"

print(calculator(10, 5, "+"))
print(calculator(10, 5, "-"))
print(calculator(10, 5, "*"))
print(calculator(10, 5, "/"))



student = { "name": "Lee",
         "age": 19,
           "grade": 4 }
print(student["name"])
print(student["age"])
print(student["grade"])

student = {
    "name": "Lee",
    "age": 19,
    "grade": 4
}

print(student["name"])
print(student["age"])
print(student["grade"])

# Now add the new key
student["school"] = "University of Nairobi"
print(student)
#again fixed by Claude

contacts = []

def add_contact(name, phone):
    contact = {"name": name, "phone": phone}
    contacts.append(contact)
    print(f"Contact {name} added!")

def view_contacts():
    if len(contacts) == 0:
        print("No contacts yet!")
    else:
        for contact in contacts:
            print(f"Name: {contact['name']} | Phone: {contact['phone']}")
def search_contact(name):
    for contact in contacts:
        if contact["name"].lower() == name.lower():
            print(f"Found! Name: {contact['name']} | Phone: {contact['phone']}")
            return
    print("Contact not found!")

def main():
    while True:
        print("\n--- Contact Book ---")
        print("1. Add contact")
        print("2. View contacts")
        print("3. Search contact")
        print("4. Quit")

        choice = input("Choose an option: ")

        if choice == "1":
            name = input("Enter name: ")
            phone = input("Enter phone: ")
            add_contact(name, phone)
        elif choice == "2":
            view_contacts()
        elif choice == "3":
            name = input("Enter name to search: ")
            search_contact(name)
        elif choice == "4":
            print("Goodbye Lee! 👋")
            break
        else:
            print("Invalid option, try again!")

main()

contact []

def add_contact(name, phone)
contact = {"name", name, "phone" : phone}
contacts.append(contact)
print(f"Contact {name} added!")

def

contacts = []

def add_contact(name, phone):
    # your code here
    contact = {"name": name, "phone": phone}
    contacts.append(contact)
    print(f"Contact {name} added!")

add_contact("Lee", "0712345678")
add_contact("John", "0798765432")
print(contacts)

def view_contacts():
  if len(contacts) == 0:
   print("No contacts yet!")
  else:
    for contact in contacts:
      print(f"Name: {contact} phone: {contact}")

  view_contacts()

  def search_contact(name):
   for contact in contacts:

    if contact("name").lower() == name.lower():
      print(f"Found! Name: {contact [name]}, Phone: {contact [phone]} ")
      return
  print("Contact not found")

#By me
contacts = []

def add_contact(name, phone):
    contact = {"name": name, "phone": phone}
    contacts.append(contact)
    print(f"Contact {name} added!")

def view_contacts():
    if len(contacts) == 0:
        print("No contacts yet!")
    else:
        for contact in contacts:
            print(f"Name: {contact['name']} | Phone: {contact['phone']}")

def search_contact(name):
    for contact in contacts:
        if contact["name"].lower() == name.lower():
            print(f"Found! Name: {contact['name']} | Phone: {contact['phone']}")
            return
    print("Contact not found!")

add_contact("Lee", "0712345678")
add_contact("John", "0798765432")
view_contacts()
search_contact("lee")

def main():
    while True:
        print("\n--- Contact Book ---")
        print("1. Add contact")
        print("2. View contacts")
        print("3. Search contact")
        print("4. Quit")

        choice = input("Choose an option: ")

        if choice == "1":
            name = input("Enter name: ")
            phone = input("Enter phone ")
            add_contact(name, phone)

                # ask for name and phone, then call add_contact()
        elif choice == "2":
            view_contacts()
            # call view_contacts()
        elif choice == "3":
            input("Enter a name ")
            search_contact(name)
            # ask for name, then call search_contact()
        elif choice == "4":
            print("Goodbye")
            break
            # print goodbye and break
        else:
            print("Invalid option")
            # print invalid option

main()